image:
  name: node:14.18
pipelines:
  branches:
    master:
      - step:
          name: publish
          caches:
            - node
          script:
            - npm ci
            - npm publish
